### ISSUE TITLE
Material Dark Theme: Errors not visible :P

### ISSUE THREAD

**Issue by mknrls** [micjamking/devtools-author#103]
Errors are not visible because of the text colors being used although warnings look totally fine.   

![error_not_visable](https://cloud.githubusercontent.com/assets/6585299/12769683/c14db20a-c9e7-11e5-9a97-0185e3b245f8.PNG)

**Comment by micjamking** [comment]
What version of the plugin are you on? This issue was resolved in v0.5.5

Reference issues: #94 #96

**Comment by mknrls** [comment]
my bad im on version 0.5.3, seem like chrome didn't update my extension..weird.

**Comment by micjamking** [comment]
You can manually update the extension by going to chrome://extensions/ and checking **Developer Mode** and then clicking the "Update extensions now" button.

![screen shot 2016-02-02 at 3 13 40 pm](https://cloud.githubusercontent.com/assets/651702/12769889/ab3fe15e-c9bf-11e5-8def-7b5670c16ae9.png)

I'm closing the issue for now (since it should be resolved), but please let me if you still experience issues after updating.
