### ISSUE TITLE
Media Query breakpoints in styles panel hard to see in dark themes

### ISSUE THREAD

**Issue by ericthayer** [micjamking/devtools-author#136]
Love the dark themes but the breakpoint text in the "styles" panel is hard to see with darker backgrounds. Below are some screenshots using the following themes:

**Material Dark**

![material-dark](https://cloud.githubusercontent.com/assets/2737007/13715764/28c2ea08-e794-11e5-880c-a6aedbdd52d1.png)

![material-dark-highlight](https://cloud.githubusercontent.com/assets/2737007/13715869/bc14ea72-e794-11e5-95e3-4056f790dbb1.png)

**Bongzilla**

![bongzilla](https://cloud.githubusercontent.com/assets/2737007/13715876/c6c8100c-e794-11e5-88ee-a36f8ceff942.png)

![bongzilla-highlight](https://cloud.githubusercontent.com/assets/2737007/13715875/c68908c6-e794-11e5-882d-eff34dc24e94.png)

**Comment by ericthayer** [comment]
I was trying to edit this locally but having a hard time targeting this text. I assumed the "Comments/Secondary Content" value was the correct one?

**Comment by micjamking** [comment]
@ericthayer Apologies for the delayed reply, the past few weeks have been very busy and hectic. Among other things, I'm recovering from an extremely _nasty_ flu :mask:.

Anyways, thank you for leaving feedback! The issue is resolved in commit 3cbd97e and is available in release [v0.6.6](https://github.com/micjamking/devtools-author/releases/tag/v0.6.6)

**Material Dark**
![screen shot 2016-03-29 at 8 12 34 pm](https://cloud.githubusercontent.com/assets/651702/14133421/a3c04728-f5ea-11e5-96bd-6e013cd4cf85.png)

**Bongzilla**
![screen shot 2016-03-29 at 8 14 04 pm](https://cloud.githubusercontent.com/assets/651702/14133451/d7d2fc5e-f5ea-11e5-8354-0acebaaf6bdb.png)

**Comment by ericthayer** [comment]
Thank you! This helps a bunch. Sorry to hear about the flu, glad you are better. Keep up the great work.
