### ISSUE TITLE
Icons on the bar not showing

### ISSUE THREAD

**Issue by scgm11** [micjamking/devtools-author#76]
Latest Chrome version
Installed as described, cant see the icons on the bars
<img width="1376" alt="screen shot 2016-01-27 at 15 34 48" src="https://cloud.githubusercontent.com/assets/984668/12624016/9dde93a6-c50b-11e5-9556-c9b8a7771040.png">

**Comment by smlombardi** [comment]
Seems theme-relatedd with the dark themes.  I used Mocha, which is a little better, although on rollover they're hidden

**Comment by LeoAJ** [comment]
+ 1, `Monokai` has the same issue.

**Comment by jano23** [comment]
Opened a similar issue before I saw this one.
It seems specific to the latest version of Chrome not the themes. 
The UI elements show up just fine in Chrome Canary with the same theme

**Comment by micjamking** [comment]
Hey guys, 

I was unable to replicate this issue on my machine using either Chrome 47 or Chrome Canary 49 on my Macbook Pro OSX 10.11.2

DevTools Author does provide a custom icon sprite image which overrides the default icons in DevTools, and my thoughts are that it's likely due to a path issue however I'll need to do further testing to confirm. 

For now, since the icon overrides are only for a couple of icons, I'm removing the custom icons styles from the stylesheet to see if this resolves the issue. Since I cannot replicate this on my machine, can someone confirm if the latest release (v0.4.7: https://github.com/micjamking/devtools-author/commit/616a9e6dd37c2472b23cf49bb96a470897dd86c1) resolves the problem?

You can check and update your extensions from the Chrome Menu > _More Tools > Extensions_ section and clicking **Update extensions now** if DevTools Author isn't showing v0.4.7.

Appreciate the feedback!
