### ISSUE TITLE
Please consider removing `-webkit-font-smoothing: antialiased;`

### ISSUE THREAD

**Issue by jamiewilson** [micjamking/devtools-author#87]
First off, thanks for making this extension! It's really awesome.

But I do find the use of font-smoothing to really diminish legibility. I made a gif to highlight the differences.

![font-smoothing](https://cloud.githubusercontent.com/assets/3308673/12663435/cdb55e74-c5ed-11e5-8a94-b6ffdb816eec.gif)

Also, I've been considering creating a dev tools theme specifically for my Sublime Text and Atom theme called [Predawn](https://packagecontrol.io/packages/Predawn). If you are ever looking to add additional color schemes, including Predawn would make my day!

**Comment by jmeas** [comment]
Just dropping in to say that Predawn looks very nice :o

**Comment by micjamking** [comment]
Hey @jamiewilson, thanks for the feedback!

I typically follow http://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/ as best practice in these matters. FWIW, DevTools Author only applyies `-webkit-font-smoothing: antialiased;` for dark themes with light text on Mac OSX. I found the default (ie. `subpixel-rendering`) made the fonts appear unnaturally bold (see screenshots below, `antialiased` on left, default/`subpixel-rendering` on right). 

![screen shot 2016-01-28 at 4 46 38 pm](https://cloud.githubusercontent.com/assets/651702/12665965/41b1a6b0-c5e0-11e5-8814-1189ca239acf.png)
![screen shot 2016-01-28 at 4 57 01 pm](https://cloud.githubusercontent.com/assets/651702/12665966/41b4a91e-c5e0-11e5-8e19-772790b4b3b3.png)

This issue becomes even more apparent on retina displays. However, I do agree the default/`subpixel-rendering` setting increases contrast (which makes sense because there's more pixels being displayed per character) and potentially legibility. I'm fine with removing it for now, however I feel this issue may come up again (albeit from the opposite angle) since this is an area that's somewhat based on preference.

**Comment by micjamking** [comment]
Also, Predawn does look mighty cool! There's a tut in the README to create additional themes for DevTools Author:

https://github.com/micjamking/devtools-author#creating-additional-themes

Let me know if you have any issues or questions.

**Comment by micjamking** [comment]
Resolved in v0.4.10  fdcc1e8

**Comment by jamiewilson** [comment]
Thank you! I need a freakin' retina screen bad.
