### ISSUE TITLE
Missing scrolling via mouse (not wheel)

### ISSUE THREAD

**Issue by SaintGerasim** [micjamking/devtools-author#89]

**Comment by micjamking** [comment]
What does that mean? Can you provide details or an example?

**Comment by SaintGerasim** [comment]
Sorry for my bad english.
I mean please add a scroll bar to "elements" and "sources".

My old laptop didn't have touchpad, so i have to scroll websites and apps using old scrollbar :(

**Comment by micjamking** [comment]
Hi @SaintGerasim, no worries I appreciate the feedback.

Are scrollbars present when DevTools Author is disabled? Custom scrollbar styles were recently removed in v0.4.11, so the extension has no impact on the systems default scroll behavior.

For instance, if you are on OSX (10.7+), scrollbars are hidden until activated by scrolling (making them invisible by default). This behavior can be changed at the system level: http://osxdaily.com/2011/08/03/show-scroll-bars-mac-os-x-lion/

For PC, I'm not as familiar, since I have not used one regularly since Windows 7. My assumption is that the behavior is similar to OSX, ie. scrollbars will appear when there is more content that needs to be scrolled.

I don't think its good practice to force scrollbars when they are not needed, so I'd like to confirm your system requirements and how scrollbars work for you currently in DevTools when the DevTools Author plugin is disabled. 

**That is, how do scrollbars work and how do they look by default, without the plugin?**

**Comment by SaintGerasim** [comment]
Hi @micjamking, i don't know what i do, or you do on your side, maybe my chrome updated extension to v0.4.11 or something else, but now scrollbars have appeared!

Seriously, at first, they're missing like in OSX (I'm Windows user), but now i can see them!

*And it's my default non-themed scrollbars, at first there been a pink, very tiny scrollbar and i actually can't scroll it to down.

Here's screenshot:
![image](https://cloud.githubusercontent.com/assets/3389326/12740963/ee2c5aea-c980-11e5-9d68-243a2a7eb70d.png)

**Comment by SaintGerasim** [comment]
@micjamking , oh and thanks for feedback!

**Comment by micjamking** [comment]
Hi @SaintGerasim; yes, you are correct, that was indeed an issue before v0.4.11, but the latest version at this time (v0.5.3) includes the fix you see. Glad you enjoy the plugin!
